### ISSUE TITLE
DropInMultiplayer makes this mod's commands not work

### ISSUE THREAD

**Issue by LordVGames** [JustDerb/RoR2-BossAntiSoftlock#3] opened 2023-11-02 19:47 UTC
Without DropInMultiplayer, the mod works just fine. Both the console command and the chat command don't work. When using the chat command, the game also says the command can't be found. There's also an error that appears in the log when I try to run one of this mod's commands:
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DropInMultiplayer.DropInMultiplayer.Console_RunCmd (On.RoR2.Console+orig_RunCmd orig, RoR2.Console self, RoR2.Console+CmdSender sender, System.String concommandName, System.Collections.Generic.List`1[T] userArgs) (at <55580ca6bbc247129930559c1ad5f8dd>:IL_0095)
DMD<>?1998183168.Hook<RoR2.Console::RunCmd>?1565474048 (RoR2.Console , RoR2.Console+CmdSender , System.String , System.Collections.Generic.List`1[T] ) (at <e0f5c4955287444c93840e93c6b9e220>:IL_000A)
DMD<>?1998183168.Trampoline<RoR2.Console::RunCmd>?671326208 (RoR2.Console , RoR2.Console+CmdSender , System.String , System.Collections.Generic.List`1[T] ) (at <e679c40427a5479396de2fe76f82a318>:IL_0020)
BossAntiSoftlock.BossAntiSoftlock.HandleCommand (On.RoR2.Console+orig_RunCmd orig, RoR2.Console self, RoR2.Console+CmdSender sender, System.String concommandName, System.Collections.Generic.List`1[T] userArgs) (at <7f43fb0d6481482a812e58099bfdeed5>:IL_0000)
DMD<>?1998183168.Hook<RoR2.Console::RunCmd>?846858752 (RoR2.Console , RoR2.Console+CmdSender , System.String , System.Collections.Generic.List`1[T] ) (at <9256428a4f75435699b2eae05dc70be2>:IL_0014)
RoR2.Console.SubmitCmd (RoR2.Console+CmdSender sender, System.String cmd, System.Boolean recordSubmit) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_00B2)
RoR2.Console.SubmitCmd (RoR2.NetworkUser sender, System.String cmd, System.Boolean recordSubmit) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0007)
RoR2.UI.ChatBox.SubmitChat () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0078)
RoR2.UI.ChatBox.Update () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0082)

[Info   : Unity Log] <color=#e5eefc><noparse>LordVGames</noparse>: <noparse>/bossreset</noparse></color>
[Info   : Unity Log] Unable to find command, try /help
```

**Comment by JustDerb** [comment] 2023-12-10 03:44
So I dug into this, and it looks like a bug in DropInMultiplayer. Specifically this line:

https://github.com/niwith/DropInMultiplayer/blob/9f31beee9ed8c594c75cdfa4de4c193bcc4adfa7/DropInMultiplayerV2/Main.cs#L165

When you type `/bossreset` this correctly runs this mods code, and then cascades to the other mod. The mod is missing a `return` statement for this if branch:

https://github.com/niwith/DropInMultiplayer/blob/9f31beee9ed8c594c75cdfa4de4c193bcc4adfa7/DropInMultiplayerV2/Main.cs#L160-L163

Because of this, `chatCommand` is null afterwards, which causes the NullReferenceException. I've opened up https://github.com/niwith/DropInMultiplayer/issues/18 to let them know to fix it.

**Comment by JustDerb** [comment] 2023-12-10 03:52
Closing this out since it's not a bug in this mod, but the other one.

**Closed as completed by JustDerb** 2023-12-10 03:52 UTC
